#!/usr/bin/env bash
# Builds the self-hosted container env file from this checkout's .env
# (docs/self-hosting-runbook.md §1, env matrix in docs/self-hosting.md).
# Copies the provider credentials, drops everything machine-local, and sets
# the production values. DB_* / REDIS_* are left out: dply:self:bootstrap
# creates dply's own database and Valkey and writes those in.
#
#   deploy/self/make-env.sh [source .env] [output]   (default: .env → ~/.dply/dply-container.env)
#   deploy/self/make-env.sh --builder                  after bootstrap: container env → ~/.dply/dply-builder.env
#
# Prints key names and warnings only, never values.
set -euo pipefail

if [ "${1:-}" = "--builder" ]; then
  # ponytail: the whole container env with the builder role on top, not the
  # runbook's least-privilege subset; trim it when builders stop needing DB access.
  src="$HOME/.dply/dply-container.env"; out="$HOME/.dply/dply-builder.env"
  grep -q '^DB_HOST=' "$src" || { echo "run dply:self:bootstrap first (no DB_HOST in $src)" >&2; exit 1; }
  umask 077
  { grep -Ev '^(DPLY_RUNTIME|REDIS_PERSISTENT|SESSION_DRIVER|TRUSTED_PROXIES|DPLY_WORKER_TIMEOUT)=' "$src"
    printf '\n# Builder role\nDPLY_RUNTIME=builder\nREDIS_PERSISTENT=false\nLOG_CHANNEL=stderr\n'; } > "$out"
  chmod 600 "$out"
  echo "wrote $out ($(grep -cE '^[A-Z0-9_]+=' "$out") keys, mode 600)"
  exit 0
fi

src="${1:-.env}"
out="${2:-$HOME/.dply/dply-container.env}"
[ -f "$src" ] || { echo "no $src" >&2; exit 1; }
mkdir -p "$(dirname "$out")"
umask 077

# Machine-local or role-specific: never copied (set below or by bootstrap).
drop='^(APP_ENV|APP_DEBUG|APP_URL|DB_[A-Z_]*|REDIS_[A-Z_]*|CACHE_STORE|CACHE_DRIVER|SESSION_[A-Z_]*|QUEUE_CONNECTION|LOG_[A-Z_]*|DPLY_RUNTIME|DPLY_SELF_SITE_ID|TRUSTED_PROXIES|APP_MAINTENANCE_[A-Z_]*|TELESCOPE_[A-Z_]*|DEBUGBAR_[A-Z_]*|PGGSSENCMODE|DPLY_TESTING_DATABASES|SECRET_VAULT_IDENTITY_PATH|SECRET_VAULT_CRITICAL_PG_PASSWORD|[A-Z_]*_PATH)='

{
  echo "# Generated by deploy/self/make-env.sh on $(date -u +%FT%TZ) from $src"
  grep -E '^[A-Z0-9_]+=' "$src" | grep -Ev "$drop"
  cat <<'EOF'

# Production, container role (docs/self-hosting.md env matrix)
APP_ENV=production
APP_DEBUG=false
APP_URL=https://edge.dply.io
DPLY_RUNTIME=container
CACHE_STORE=redis
SESSION_DRIVER=redis
QUEUE_CONNECTION=redis
REDIS_CLIENT=phpredis
REDIS_PERSISTENT=true
LOG_CHANNEL=stderr
TRUSTED_PROXIES=*
DPLY_WORKER_TIMEOUT=900
APP_MAINTENANCE_DRIVER=cache
APP_MAINTENANCE_STORE=redis
PGGSSENCMODE=disable
DB_CONNECTION=pgsql
DB_SSLMODE=require
EOF
} > "$out"
chmod 600 "$out"

val() { grep -E "^$1=" "$out" | tail -1 | cut -d= -f2- | tr -d '"'; }
warn=0
for k in APP_KEY APP_NAME DPLY_EDGE_CF_API_TOKEN DPLY_EDGE_CF_ACCOUNT_ID DPLY_EDGE_CF_DISPATCH_NAMESPACE \
         DPLY_EDGE_R2_BUCKET DPLY_EDGE_R2_ACCESS_KEY DPLY_EDGE_R2_SECRET DPLY_EDGE_CONTAINER_DEPLOY_API_TOKEN \
         DPLY_VALKEY_API_URL DPLY_VALKEY_TOKEN STRIPE_KEY STRIPE_SECRET STRIPE_WEBHOOK_SECRET \
         GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET MAIL_MAILER MAIL_FROM_ADDRESS PLATFORM_ADMIN_EMAILS; do
  [ -n "$(val "$k")" ] || { echo "MISSING  $k"; warn=1; }
done
case "$(val STRIPE_SECRET)" in sk_test_*|rk_test_*) echo "WARN     STRIPE_SECRET is a test key (fine for private beta, not for charging)"; warn=1;; esac
case "$(val MAIL_HOST)" in ''|localhost|127.*|mailpit|mailhog) [ "$(val MAIL_MAILER)" = smtp ] && { echo "WARN     MAIL_HOST is local: production mail won't send"; warn=1; };; esac
case "$(val GITHUB_OAUTH_REDIRECT_URI)" in ''|https://edge.dply.io/*) ;; *) echo "WARN     GITHUB_OAUTH_REDIRECT_URI is not on https://edge.dply.io"; warn=1;; esac

echo "wrote $out ($(grep -cE '^[A-Z0-9_]+=' "$out") keys, mode 600)"
[ "$warn" = 0 ] && echo "all required keys present" || echo "fix the lines above in $out, then re-run bootstrap --dry-run"
