<?php

declare(strict_types=1);

namespace App\Modules\Edge\Support;

use App\Models\Site;

/**
 * Puts dply-entry.js in front of every Worker site upload (ruling
 * r-72p0gkdn9dqwxqha). It re-exports the app's own entry, so the app's
 * Durable Object and Workflow classes still resolve, and hands the app an env
 * where resources look the same as on a container:
 *
 *   - State (durable_object): env.NAME.fetch('https://state/key') reaches one
 *     EdgeState object in the site's dply-state script. The raw namespace is
 *     env.NAME.namespace.
 *   - Another app (service): env.NAME.fetch('/path') goes to that app's live
 *     URL with the same method, headers, and body.
 */
final class EdgeWorkerEntryWrapper
{
    public const ENTRY = 'dply-entry.js';

    /**
     * @param  array<string, string>  $modules
     * @return array{0: string, 1: array<string, string>}
     */
    public static function wrap(Site $site, string $entry, array $modules): array
    {
        if ($entry === self::ENTRY || isset($modules[self::ENTRY])) {
            return [$entry, $modules];
        }

        $state = [];
        $peers = [];
        $origins = collect(EdgeContainerConnections::peerApps($site))->pluck('origin', 'id');
        foreach (EdgeContainerConnections::for($site) as $connection) {
            if ($connection['asleep']) {
                continue;
            }
            if ($connection['kind'] === 'durable_object') {
                $state[] = $connection['name'];
            } elseif ($connection['kind'] === 'service' && isset($origins[$connection['target']])) {
                $peers[$connection['name']] = (string) $origins[$connection['target']];
            }
        }

        $modules[self::ENTRY] = self::source($entry, $state, $peers);

        return [self::ENTRY, $modules];
    }

    /**
     * A peer's live URL is usually on the platform zone, and Cloudflare
     * refuses a Worker fetch to its own zone (error 1042) unless the script
     * fetches strictly over the public internet.
     *
     * @param  list<string>  $flags
     * @return list<string>
     */
    public static function compatibilityFlags(Site $site, array $flags): array
    {
        foreach (EdgeContainerConnections::for($site) as $connection) {
            if ($connection['kind'] === 'service' && ! $connection['asleep']) {
                return array_values(array_unique([...$flags, 'global_fetch_strictly_public']));
            }
        }

        return $flags;
    }

    /**
     * @param  list<string>  $state
     * @param  array<string, string>  $peers
     */
    public static function source(string $entry, array $state, array $peers): string
    {
        $import = json_encode('./'.preg_replace('#^\./#', '', $entry), JSON_UNESCAPED_SLASHES);
        $stateJson = json_encode($state, JSON_UNESCAPED_SLASHES);
        $peersJson = json_encode((object) $peers, JSON_UNESCAPED_SLASHES);

        return <<<JS
// Generated by dply (EdgeWorkerEntryWrapper). Edits are overwritten on deploy.
import app from {$import};
export * from {$import};

const STATE = {$stateJson};
const PEERS = {$peersJson};

function peer(origin) {
  return {
    fetch(input, init) {
      const request = new Request(input instanceof Request ? input : new URL(String(input), origin), init);
      const target = new URL(origin);
      const url = new URL(request.url);
      target.pathname = url.pathname;
      target.search = url.search;
      return fetch(new Request(target, request));
    },
  };
}

function state(namespace) {
  return {
    namespace,
    fetch(input, init) {
      const request = new Request(input instanceof Request ? input : new URL(String(input), 'https://state'), init);
      return namespace.get(namespace.idFromName('default')).fetch(request);
    },
  };
}

function withDply(env) {
  if (STATE.length === 0 && Object.keys(PEERS).length === 0) return env;
  const out = Object.assign({}, env);
  for (const name of STATE) if (env[name]) out[name] = state(env[name]);
  for (const [name, origin] of Object.entries(PEERS)) out[name] = peer(origin);
  return out;
}

// Queue batches from the platform Worker (EdgeQueueConsumers). The reply
// says which messages to retry; everything else is acknowledged.
async function runQueue(request, env, ctx) {
  if (typeof app.queue !== 'function') return Response.json({ retryAll: true, error: 'This app has no queue handler.' });
  const { queue, messages } = await request.json();
  const retries = new Map();
  let retryAll = null;
  const batch = {
    queue,
    messages: messages.map((m) => ({
      id: m.id,
      body: m.body,
      attempts: m.attempts,
      timestamp: new Date(m.timestamp),
      ack() { retries.delete(m.id); },
      retry(options) { retries.set(m.id, options?.delaySeconds ?? null); },
    })),
    ackAll() { retries.clear(); retryAll = null; },
    retryAll(options) { retryAll = options?.delaySeconds ?? 0; },
  };
  try {
    await app.queue(batch, withDply(env), ctx);
  } catch (error) {
    return Response.json({ retryAll: true, error: String(error) });
  }
  if (retryAll !== null) return Response.json({ retryAll: true, delaySeconds: retryAll || undefined });
  return Response.json({ retry: [...retries].map(([id, delaySeconds]) => ({ id, delaySeconds: delaySeconds ?? undefined })) });
}

function isQueueDelivery(request, env) {
  return request.method === 'POST'
    && typeof env.DPLY_QUEUE_TOKEN === 'string'
    && new URL(request.url).pathname === '/__dply/queue'
    && request.headers.get('x-dply-queue-token') === env.DPLY_QUEUE_TOKEN;
}

const handler = {};
for (const key of ['fetch', 'scheduled', 'queue', 'email', 'tail', 'trace']) {
  if (app && typeof app[key] === 'function') {
    handler[key] = (event, env, ctx) => app[key](event, withDply(env), ctx);
  }
}
if (app && typeof app === 'object') {
  const appFetch = handler.fetch;
  handler.fetch = (request, env, ctx) => {
    if (isQueueDelivery(request, env)) return runQueue(request, env, ctx);
    return appFetch ? appFetch(request, env, ctx) : new Response('Not found', { status: 404 });
  };
}

// A class entry (WorkerEntrypoint) is passed through as is.
export default typeof app === 'function' ? app : handler;

JS;
    }
}
