<?php

declare(strict_types=1);

namespace App\Modules\Edge\Support;

/**
 * Writes a Wrangler config file from Laravel edge config for production deploys.
 */
class EdgeWranglerConfigGenerator
{
    public function outputPath(): string
    {
        return base_path('packages/edge-worker/wrangler.generated.toml');
    }

    public function write(?EdgeDeliveryContext $context = null): string
    {
        $context ??= EdgeDeliveryContext::platform();

        if ($context->r2Bucket === '' || $context->kvNamespaceId === '') {
            throw new \RuntimeException('R2 bucket and KV namespace id are required to generate Wrangler config.');
        }

        $lines = [
            '# Generated by dply — do not edit. Run: php artisan edge:worker:deploy',
            'name = '.json_encode($context->workerScriptName, JSON_UNESCAPED_SLASHES),
            'main = "src/index.ts"',
            'compatibility_date = "2024-11-01"',
            '',
            '[vars]',
            'ENVIRONMENT = "production"',
        ];

        $analyticsDataset = trim((string) config('edge.cloudflare.analytics_dataset', ''));
        if ($analyticsDataset !== '') {
            $lines[] = '';
            $lines[] = '[[analytics_engine_datasets]]';
            $lines[] = 'binding = "EDGE_ANALYTICS"';
            $lines[] = 'dataset = '.json_encode($analyticsDataset, JSON_UNESCAPED_SLASHES);
        }

        $lines = array_merge($lines, [
            '',
            '[[r2_buckets]]',
            'binding = "ARTIFACTS"',
            'bucket_name = '.json_encode($context->r2Bucket, JSON_UNESCAPED_SLASHES),
            '',
            '[[kv_namespaces]]',
            'binding = "HOST_MAP"',
            'id = '.json_encode($context->kvNamespaceId, JSON_UNESCAPED_SLASHES),
        ]);

        if ($context->cacheKvNamespaceId !== '') {
            $lines = array_merge($lines, [
                '',
                '[[kv_namespaces]]',
                'binding = "EDGE_CACHE"',
                'id = '.json_encode($context->cacheKvNamespaceId, JSON_UNESCAPED_SLASHES),
            ]);
        }

        // Workers for Platforms dispatch binding — require a concrete
        // namespace *id*, not just a configured name. Name-only scopes
        // still advertise SSR via ensure-on-create; wrangler must not
        // bind DISPATCHER on accounts without WfP (deploy fails with
        // Cloudflare error 10121). Static + hybrid keep working either way.
        if ($context->dispatchNamespaceId !== '' && $context->dispatchNamespaceName !== '') {
            $lines = array_merge($lines, [
                '',
                '[[dispatch_namespaces]]',
                'binding = "DISPATCHER"',
                'namespace = '.json_encode($context->dispatchNamespaceName, JSON_UNESCAPED_SLASHES),
            ]);
        }

        if ($context->workerRoutes !== []) {
            $lines[] = '';
            foreach ($context->workerRoutes as $pattern) {
                $zoneName = self::zoneNameForRoute($pattern, $context->workerZoneName);
                if ($zoneName === '') {
                    continue;
                }
                $lines[] = '[[routes]]';
                $lines[] = 'pattern = '.json_encode($pattern, JSON_UNESCAPED_SLASHES);
                $lines[] = 'zone_name = '.json_encode($zoneName, JSON_UNESCAPED_SLASHES);
                $lines[] = '';
            }
        }

        $contents = rtrim(implode("\n", $lines))."\n";
        file_put_contents($this->outputPath(), $contents);

        return $this->outputPath();
    }

    public static function zoneNameForRoute(string $pattern, string $fallbackZone): string
    {
        if (preg_match('#^\*\.([^/*]+)/\*$#', trim($pattern), $matches) === 1) {
            return strtolower($matches[1]);
        }

        return strtolower(trim($fallbackZone));
    }
}
